Repository jsk-ros-pkg/jsk_demos, pull requests merged in 2022-06, with the labels that each got.

#1354 Update welcome_to_jsk_fetch
  welcome_to_jsk_fetch/README.md
  welcome_to_jsk_fetch/euslisp/fetch-interface-utils.l
  welcome_to_jsk_fetch/euslisp/fetch-pull-arm.l
  welcome_to_jsk_fetch/euslisp/guide.l
  welcome_to_jsk_fetch/euslisp/language-utils.l
  welcome_to_jsk_fetch/euslisp/roseus-utils.l
  welcome_to_jsk_fetch/euslisp/speech-recognition-client.l
  welcome_to_jsk_fetch/euslisp/utils.l
  welcome_to_jsk_fetch/fetch-navigation.l
  welcome_to_jsk_fetch/fetch_navigation.launch
  welcome_to_jsk_fetch/launch/guide.launch
  welcome_to_jsk_fetch/launch/holding_hands.launch
  welcome_to_jsk_fetch/launch/people_detection.launch
  welcome_to_jsk_fetch/node_scripts/people_pose_2d_to_3d.py
  welcome_to_jsk_fetch/node_scripts/people_pose_aggregated_detector.py
  welcome_to_jsk_fetch/package.xml
  welcome_to_jsk_fetch/welcome-to-jsk.l
  welcome_to_jsk_fetch/welcome_to_jsk_fetch.launch
  welcome_to_jsk_fetch/welcome_to_jsk_fetch.rosinstall
Labels: MergeOK

#1352 [jsk_maps] Frame id cannot start with a '/' in tf2
  jsk_maps/tools/publish_spot.l
Labels: MergeOK

#1350 Add enshu room to eng2 1f map
  jsk_maps/raw_maps/eng2-1f-0.05.pgm
  jsk_maps/raw_maps/eng2-1f-0.05_keepout.pgm
  jsk_maps/raw_maps/eng2-1f-0.05_keepout.xcf
Labels: MergeOK

#1337 add rwt_teleop
  rwt_teleop/.gitignore
  rwt_teleop/CMakeLists.txt
  rwt_teleop/README.md
  rwt_teleop/apps/app.installed
  rwt_teleop/apps/rwt_teleop/rwt_teleop.app
  rwt_teleop/apps/rwt_teleop/rwt_teleop.interface
  rwt_teleop/apps/rwt_teleop/rwt_teleop.png
  rwt_teleop/apps/rwt_teleop/rwt_teleop.xml
  rwt_teleop/euslisp/dual_panda-realtime-ik.l
  rwt_teleop/euslisp/pr2-realtime-ik.l
  rwt_teleop/launch/dual_panda_screenpoint_teleop.launch
  rwt_teleop/launch/pr2_screenpoint_teleop.launch
  rwt_teleop/launch/tabletop_segmentation.launch
  rwt_teleop/package.xml
  rwt_teleop/scripts/draw_force_on_image.py
  rwt_teleop/scripts/dual_panda_rwt_command_parser.py
  rwt_teleop/scripts/point_to_tf.py
  rwt_teleop/scripts/pose_to_tf.py
  rwt_teleop/scripts/pr2_rwt_command_parser.py
  rwt_teleop/scripts/tablis_gripper.py
  rwt_teleop/setup.py
  rwt_teleop/src/rwt_teleop/__init__.py
  rwt_teleop/src/rwt_teleop/dual_arm_rwt_command_parser.py
  rwt_teleop/www/3rdparty/ros/js/eventemitter2.js
  rwt_teleop/www/3rdparty/ros/js/roslib.js
  rwt_teleop/www/css/rwt_teleop.css
  rwt_teleop/www/index.html
  rwt_teleop/www/js/rwt_teleop_main.js
  rwt_teleop/www/pr2.jpg
Labels: MergeOK

#1344 [jsk_maps] update 73B2 kitchen map
  jsk_maps/raw_maps/eng2-7f-0.05.pgm
  jsk_maps/raw_maps/eng2-7f-0.05.raw.pgm
  jsk_maps/raw_maps/eng2-7f-0.05.xcf
  jsk_maps/raw_maps/eng2-7f-0.05_keepout.pgm
  jsk_maps/raw_maps/eng2-7f-0.05_keepout.xcf
Labels: MergeOK

#1288 [detect_cans_in_fridge_201202] update readme
  detect_cans_in_fridge_201202/README.md
Labels: MergeOK

#1353 [elevator_move_base_pr2] fix opencv for opencv4
  elevator_move_base_pr2/src/color_point_detector.cpp
Labels: MergeOK, please fix

#1306 add comment at dump-map-info
  jsk_maps/src/dump-map-info.l
Labels: hacktoberfest-accepted
